@base_url = http://localhost:8080
@headerTypeJson = Content-Type: application/json
@product_id = 638746991637

###

POST {{base_url}}/products HTTP/1.1
{{headerTypeJson}}

{
    "name": "notebook",
    "price": 99.90,
    "description": "notebook dell inspiron serie 5000",
    "category": "eletronics"
}

###

GET {{base_url}}/products/{{product_id}}  HTTP/1.1

###

PATCH {{base_url}}/products/{{product_id}} HTTP/1.1
{{headerTypeJson}}

{
    "price": 99.99,
    "description": "notebook dell inspiron serie 9000"
}

###

DELETE {{base_url}}/products/{{product_id}} HTTP/1.1